save_root: "S:/School/Fall2021/UCLA/Capstone/Code/Pokemon-cards/scraping_code/results"
save_name: "console_data"
py_implementation: "ebay_auctions"
site_specific_search_root: "/b/CCG-Sealed-Packs/183456?Features=Special%2520Edition%2520Box&Game=Pok%25C3%25A9mon%2520TCG&Language=English&Set=Celebrations%253A%2520Classic%2520Collection&Year%2520Manufactured=2021&rt=nc&mag=1&LH_Sold=1"
max_search_page: 1